### ISSUE TITLE
Can I use your WASM code?

### ISSUE THREAD

**Issue by mbarkhau** [ivanceras/ivanceras.github.io#2]
Hi @ivanceras,

I'm working on an ascii diagram editor, you can see it here: https://mbarkhau.keybase.pub/ascii-draw.html

I've only tested in chrome, so ymmv. Anyway, I would like to integrate the WASM code from you're svgbob-editor page. Is that ok with you? I'll be happy to make the editor open source if you would like to use it.

Cheers
Manuel

**Comment by mbarkhau** [comment]
I've had a look at how to compile svgbob using wasm-bindgen. It seems like some work that maybe you've already done, but haven't open sourced. I can see that the svgbob-editor is itself implemented using wasm, so there's probably lots of dom logic that is unrelated to the core svgbob api that I'm looking for.

Is there anything you have time to help me with to get this working?

**Comment by ivanceras** [comment]
Hi @mbarkhau , the svgbob-editor is not opensourced.

**Comment by mbarkhau** [comment]
Ok, thanks for the update. I've implemented a server side renderer in the meantime.

https://mbarkhau.keybase.pub/drawAscii/

**Comment by ivanceras** [comment]
That's cool, what framework are you using? I was using yew on my svgbob-editor, but I wanted to port it over to [sauron](https://github.com/ivanceras/sauron)

**Comment by mbarkhau** [comment]
Server side is just flask and https://pypi.org/project/markdown-svgbob/
